export type Prefecture = {
  id: string
  nameJa: string
  nameEn: string
  regionJa: string
  regionEn: string
}

export const prefectures: Prefecture[] = [
  { id: "0", nameJa: "", nameEn: "", regionJa: "", regionEn: "" },
  { id: "1", nameJa: "北海道", nameEn: "hokkaido", regionJa: "北海道", regionEn: "hokkaido" },
  { id: "2", nameJa: "青森県", nameEn: "aomori", regionJa: "東北", regionEn: "tohoku" },
  { id: "3", nameJa: "岩手県", nameEn: "iwate", regionJa: "東北", regionEn: "tohoku" },
  { id: "4", nameJa: "宮城県", nameEn: "miyagi", regionJa: "東北", regionEn: "tohoku" },
  { id: "5", nameJa: "秋田県", nameEn: "akita", regionJa: "東北", regionEn: "tohoku" },
  { id: "6", nameJa: "山形県", nameEn: "yamagata", regionJa: "東北", regionEn: "tohoku" },
  { id: "7", nameJa: "福島県", nameEn: "fukushima", regionJa: "東北", regionEn: "tohoku" },
  { id: "8", nameJa: "茨城県", nameEn: "ibaraki", regionJa: "関東", regionEn: "kanto" },
  { id: "9", nameJa: "栃木県", nameEn: "tochigi", regionJa: "関東", regionEn: "kanto" },
  { id: "10", nameJa: "群馬県", nameEn: "gunma", regionJa: "関東", regionEn: "kanto" },
  { id: "11", nameJa: "埼玉県", nameEn: "saitama", regionJa: "関東", regionEn: "kanto" },
  { id: "12", nameJa: "千葉県", nameEn: "chiba", regionJa: "関東", regionEn: "kanto" },
  { id: "13", nameJa: "東京都", nameEn: "tokyo", regionJa: "関東", regionEn: "kanto" },
  { id: "14", nameJa: "神奈川県", nameEn: "kanagawa", regionJa: "関東", regionEn: "kanto" },
  { id: "15", nameJa: "新潟県", nameEn: "niigata", regionJa: "中部", regionEn: "chubu" },
  { id: "16", nameJa: "富山県", nameEn: "toyama", regionJa: "中部", regionEn: "chubu" },
  { id: "17", nameJa: "石川県", nameEn: "ishikawa", regionJa: "中部", regionEn: "chubu" },
  { id: "18", nameJa: "福井県", nameEn: "fukui", regionJa: "中部", regionEn: "chubu" },
  { id: "19", nameJa: "山梨県", nameEn: "yamanashi", regionJa: "中部", regionEn: "chubu" },
  { id: "20", nameJa: "長野県", nameEn: "nagano", regionJa: "中部", regionEn: "chubu" },
  { id: "21", nameJa: "岐阜県", nameEn: "gifu", regionJa: "中部", regionEn: "chubu" },
  { id: "22", nameJa: "静岡県", nameEn: "shizuoka", regionJa: "中部", regionEn: "chubu" },
  { id: "23", nameJa: "愛知県", nameEn: "aichi", regionJa: "中部", regionEn: "chubu" },
  { id: "24", nameJa: "三重県", nameEn: "mie", regionJa: "近畿", regionEn: "kinki" },
  { id: "25", nameJa: "滋賀県", nameEn: "shiga", regionJa: "近畿", regionEn: "kinki" },
  { id: "26", nameJa: "京都府", nameEn: "kyoto", regionJa: "近畿", regionEn: "kinki" },
  { id: "27", nameJa: "大阪府", nameEn: "osaka", regionJa: "近畿", regionEn: "kinki" },
  { id: "28", nameJa: "兵庫県", nameEn: "hyogo", regionJa: "近畿", regionEn: "kinki" },
  { id: "29", nameJa: "奈良県", nameEn: "nara", regionJa: "近畿", regionEn: "kinki" },
  { id: "30", nameJa: "和歌山県", nameEn: "wakayama", regionJa: "近畿", regionEn: "kinki" },
  { id: "31", nameJa: "鳥取県", nameEn: "tottori", regionJa: "中国", regionEn: "chugoku" },
  { id: "32", nameJa: "島根県", nameEn: "shimane", regionJa: "中国", regionEn: "chugoku" },
  { id: "33", nameJa: "岡山県", nameEn: "okayama", regionJa: "中国", regionEn: "chugoku" },
  { id: "34", nameJa: "広島県", nameEn: "hiroshima", regionJa: "中国", regionEn: "chugoku" },
  { id: "35", nameJa: "山口県", nameEn: "yamaguchi", regionJa: "中国", regionEn: "chugoku" },
  { id: "36", nameJa: "徳島県", nameEn: "tokushima", regionJa: "四国", regionEn: "shikoku" },
  { id: "37", nameJa: "香川県", nameEn: "kagawa", regionJa: "四国", regionEn: "shikoku" },
  { id: "38", nameJa: "愛媛県", nameEn: "ehime", regionJa: "四国", regionEn: "shikoku" },
  { id: "39", nameJa: "高知県", nameEn: "kochi", regionJa: "四国", regionEn: "shikoku" },
  { id: "40", nameJa: "福岡県", nameEn: "fukuoka", regionJa: "九州", regionEn: "kyushu" },
  { id: "41", nameJa: "佐賀県", nameEn: "saga", regionJa: "九州", regionEn: "kyushu" },
  { id: "42", nameJa: "長崎県", nameEn: "nagasaki", regionJa: "九州", regionEn: "kyushu" },
  { id: "43", nameJa: "熊本県", nameEn: "kumamoto", regionJa: "九州", regionEn: "kyushu" },
  { id: "44", nameJa: "大分県", nameEn: "oita", regionJa: "九州", regionEn: "kyushu" },
  { id: "45", nameJa: "宮崎県", nameEn: "miyazaki", regionJa: "九州", regionEn: "kyushu" },
  { id: "46", nameJa: "鹿児島県", nameEn: "kagoshima", regionJa: "九州", regionEn: "kyushu" },
  { id: "47", nameJa: "沖縄県", nameEn: "okinawa", regionJa: "九州", regionEn: "kyushu" },
]
